# TODO: add transmission-port variable

default:
	just --list

# verify & delete bad checksums
a:
	#!/usr/bin/env bash
	cd {{invocation_directory()}}
	~xjjk/Missing-Checksums.py -axxh | cut -d"/" -f1 | uniq | parallel -j2 -n1 echo rm "\"{}*.xxh\"" | tee | sh
	cksums.py -axxh -j0 *xxh | cut -d" " -f2- | cut -d "/" -f1 | sort | uniq | parallel -j1 echo rm "\"{}.*xxh\"" | tee | sh

# verify torrents w/out xxh
b:
	#!/usr/bin/env bash
	cd {{invocation_directory()}}
	~xjjk/Missing-Checksums.py -axxh | cut -d"/" -f1 | uniq | xargs -I{} ~xjjk/tsmu.py fn {} --ids | xargs -I{} transmission-remote -t {} --verify

# recreate xxh for torrents w/out them
c:
	#!/usr/bin/env bash
	cd {{invocation_directory()}}
	~xjjk/tsmu.py fp $(pwd) -c incomplete | sed '/^[[:blank:]]*$/ d' | rg -F '[]'
	~xjjk/Missing-Checksums.py -axxh | cut -d"/" -f1 | uniq | xargs -n1 Create-SHA1-for-directory.sh | rg xxhsum | tee | sh

# verify ALL torrents
va:
	#!/usr/bin/env bash
	cd {{invocation_directory()}}
	~/tsmu.py fp $(pwd) --ids | tr -d '\n' | xargs --delimiter=, -I{} echo transmission-remote -t {} --verify

# verify sfv files
vs:
	fdfind -e sfv -x sh -c "cd \"{//}\" && cksfv -iqf \"{/}\""

dupes:
	#!/usr/bin/env bash
	cd {{invocation_directory()}}
	python3 ~/check-dupes.py
